---
equinix_metal_project_name: "{{ env_type }}-{{ guid }}"

equinix_metal_api_uri: https://api.equinix.com/metal/v1
equinix_metal_api_retries: 10
equinix_metal_api_delay: 30

# Defaults for devices
equinix_metal_default_os: centos_8
