---
# - name: Create Equinix Metal project
#   kacket_project:
#     name: "{{ equinix_metal_project_name }}"
#     org_id: "{{ equinix_metal_organization_id }}"
#     payment_method: "{{ equinix_metal_payment_method_id }}"
# https://metal.equinix.com/developers/api/projects/
- name: Lookup for project
  changed_when: false
  uri:
    url: "{{ equinix_metal_api_uri }}/projects"
    headers:
      X-Auth-Token: "{{ equinix_metal_api_token }}"
  register: r_projects
  retries: "{{ equinix_metal_api_retries }}"
  delay: "{{ equinix_metal_api_delay }}"
  until: r_projects is succeeded

- name: Save project ids
  vars:
    _query: >-
      projects[?name=='{{ equinix_metal_project_name }}'].id
  set_fact:
    equinix_metal_project_ids: "{{ r_projects.json | json_query(_query) }}"


- when: equinix_metal_project_ids | length > 1
  fail:
    msg: >-
      There is more than one project matching
      name {{ equinix_metal_project_name }}

- when: equinix_metal_project_ids | length == 1
  block:
    - debug:
        msg: >-
          Project {{ equinix_metal_project_name }} found:
          {{ equinix_metal_project_ids[0] }}

    - name: Save project id as equinix_metal_project_id
      set_fact:
        equinix_metal_project_id: "{{ equinix_metal_project_ids[0] }}"

- when: equinix_metal_project_ids | length == 0
  block:
    - name: Create Equinix Metal project
      uri:
        method: POST
        url: "{{ equinix_metal_api_uri }}/projects"
        headers:
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        body_format: json
        follow_redirects: true
        status_code:
          - 200
          - 201
        body:
          name: "{{ equinix_metal_project_name }}"
          organization_id: "{{ equinix_metal_organization_id }}"
          payment_method_id: "{{ equinix_metal_payment_method_id }}"
      register: r_project
      retries: "{{ equinix_metal_api_retries }}"
      delay: "{{ equinix_metal_api_delay }}"
      until: r_project is succeeded
      changed_when: true

    - debug:
        var: r_project
        verbosity: 3

    - name: Save project id as equinix_metal_project_id
      set_fact:
        equinix_metal_project_id: "{{ r_project.json.id }}"
