---
################################################################################
################################################################################
############ Step 006 Destroy Workshop using workshop_prefix
################################################################################
################################################################################

- import_playbook: setup_runtime.yml

- name: Detect in what region the stack is
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  tasks:
    - when:
        - cloud_provider == 'ec2'
        - target_regions is not defined
      include_tasks: cloud_providers/ec2_detect_region_tasks.yml

- import_playbook: >-
    {{ lookup('first_found', {
         'files': [ 'destroy_env.yml',
                    cloud_provider + '_destroy_env.yml'
                  ],
         'paths': [ 'configs/' + env_type,
                    'cloud_providers/'
                  ]
       })
    }}

- name: Post Destroy Hooks
  import_playbook: hooks/post_destroy.yaml
  tags:
    - dynamic_roles
    - post_destroy
    - post_destroy_tasks

- import_playbook: save_output_dir.yml

- import_playbook: completion_callback.yml
