---
- name: Install Infra dynamic workloads
  hosts: localhost
  gather_facts: false
  tags:
    - dynamic_workloads
  tasks:
    - name: Process workloads
      loop: "{{ agnosticd_infra_workloads | default([]) }}"
      loop_control:
        loop_var: _workload
        label: "{{ _workload.name }}"
      include_role:
        name: "{{ _workload.name }}"
        defaults_from: "{{ _workload.defaults_from | default('main') }}"
        handlers_from: "{{ _workload.defaults_from | default('main') }}"
        tasks_from: "{{ _workload.tasks_from | default('main') }}"
        vars_from: "{{ _workload.vars_from | default('main') }}"
