---
# vim: set ft=ansible:

################################################################################
################################################################################
############ Step 0000 Setup Runtime
################################################################################
################################################################################

- import_playbook: setup_runtime.yml
  tags:
    - must
    - step0000
    - setup_runtime

################################################################################
################################################################################
############ Step 000 Pre Infrastructure Deploy Tasks
################################################################################
################################################################################

- import_playbook: "./configs/{{ env_type }}/pre_infra.yml"
  tags:
    - step000
    - pre_infra_tasks

- name: Pre Infra Dynamic Roles
  import_playbook: hooks/pre_infra.yml
  tags:
    - step000
    - dynamic_roles
    - pre_infra
    - pre_infra_tasks

#################################################################################
#################################################################################
############ Step 001 Deploy Infrastructure
#################################################################################
#################################################################################

# Use first found:
# - infra.yml in config directory
# - common cloud_provider
- vars:
    findme:
      - configs/{{ env_type }}/infra.yml
      - cloud_providers/{{ cloud_provider }}_infrastructure_deployment.yml
  import_playbook: "{{ lookup('first_found', findme) }}"
  tags:
    - step001
    - deploy_infrastructure
    - infra
    - infra_tasks

- name: Infra Dynamic Roles
  import_playbook: hooks/infra.yml
  tags:
    - step001
    - deploy_infrastructure
    - infra
    - infra_tasks
    - dynamic_roles
    - deploy_infrastructure

################################################################################
################################################################################
########### Step 002 Post Infrastructure Deploy Tasks
################################################################################
################################################################################

- import_playbook: "./configs/{{ env_type }}/post_infra.yml"
  tags:
    - step002
    - post_infra
    - post_infra_tasks

- name: Post Infra Dynamic Roles
  import_playbook: hooks/post_infra.yml
  tags:
    - step002
    - dynamic_roles
    - post_infra
    - post_infra_tasks

################################################################################
################################################################################
########### Step 003 Pre Software Deploy Tasks
################################################################################
################################################################################

- name: Pre Software
  import_playbook: "./configs/{{ env_type }}/pre_software.yml"
  tags:
    - step003
    - pre_software
    - pre_software_tasks

- name: Pre Software Dynamic Roles
  import_playbook: hooks/pre_software.yml
  tags:
    - step003
    - pre_software
    - pre_software_tasks
    - dynamic_roles

##################################################################################
##################################################################################
############ Step 004 Software Deploy Tasks
##################################################################################
##################################################################################

- name: Environment '{{ env_type }}' specific software playbook
  import_playbook: "./configs/{{ env_type }}/software.yml"
  tags:
    - step004
    - deploy_software
    - software
    - software_tasks

- name: Software Playbook '{{ software_to_deploy | d('none') }}'
  import_playbook: "./software_playbooks/{{ software_to_deploy | d('none') }}.yml"
  tags:
    - step004
    - deploy_software
    - software
    - software_tasks

- name: Software Dynamic Roles
  import_playbook: hooks/software.yml
  tags:
    - step004
    - deploy_software
    - software
    - software_tasks
    - dynamic_roles

################################################################################
################################################################################
############ Step 005 Post Software Deploy Tasks
################################################################################
################################################################################

- import_playbook: "./configs/{{ env_type }}/post_software.yml"
  tags:
    - step005
    - post_software
    - post_software_tasks

- name: Post Software Dynamic Roles
  import_playbook: hooks/post_software.yml
  tags:
    - step005
    - post_software
    - post_software_tasks
    - dynamic_roles

- import_playbook: save_output_dir.yml

- import_playbook: completion_callback.yml
