FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
RUN microdnf install -y python3 openssh

LABEL maintainer="Guillaume Core (fridim) <gucore@redhat.com>"

RUN pip3 install --upgrade pip
RUN pip3 install ansible==4.1.0 jmespath jsonschema
RUN pip3 install packet-python

USER ${USER_UID}
