---
type: array
items:
  type: object
  properties:
    name:
      type: string
    type:
      type: string
    count:
      type:
        - number
        - string
  required:
    - name
    - type
    - count
