---
- import_playbook: ../include_vars.yml

- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Run infra-equinix-metal-resources-destroy
      include_role:
        name: infra-equinix-metal-resources-destroy
