---
- name: Generate SSH keys
  command: >-
    ssh-keygen -b 2048 -t rsa -q -N ""
    -f "{{ output_dir }}/{{ guid }}_id_rsa"
  args:
    creates: "{{ output_dir }}/{{ guid }}_id_rsa"

- name: Set permission
  file:
    path: "{{ output_dir }}/{{ guid }}_id_rsa"
    mode: 0400

- name: Generate SSH pub key
  shell: >-
    ssh-keygen -y -f "{{ output_dir }}/{{ guid }}_id_rsa"
    > "{{ output_dir }}/{{ guid }}_id_rsa.pub"
  args:
    creates: "{{output_dir}}/{{ guid }}_id_rsa.pub"

- name: Set permission
  file:
    path: "{{ output_dir }}/{{ guid }}_id_rsa.pub"
    mode: 0400

# Doesn't work for project ssh keys
# - name: Create SSH key file
#   packet_sshkey:
#     auth_token: "{{ equinix_metal_api_token }}"
#     key_file: "{{ output_dir }}/{{ guid }}_id_rsa.pub"
#     label: "{{ guid }}"
#

# https://metal.equinix.com/developers/api/ssh-keys/
- name: Create SSH key for project
  changed_when: >-
    not "Key already exists" in r_key.json.errors | default([])
  failed_when: >-
    not r_key is succeeded
    and not "Key already exists" in r_key.json.errors | default([])
  uri:
    method: POST
    url: >-
      {{ equinix_metal_api_uri }}/projects/{{ equinix_metal_project_id }}/ssh-keys
    headers:
      X-Auth-Token: "{{ equinix_metal_api_token }}"
    status_code:
      - 200
      - 201
    body_format: json
    body:
      label: "{{ guid }}"
      key: >-
        {{ lookup('file',
        output_dir + "/" + guid + "_id_rsa.pub") }}
  register: r_key
  retries: "{{ equinix_metal_api_retries }}"
  delay: "{{ equinix_metal_api_delay }}"
  until: r_key is succeeded
